version: "3"
services:
  grafana:
    image: grafana/grafana:8.4.2
    ports:
      - '3000:3000'
      - '3333:3333'
    environment:
      - 'GF_SECURITY_ADMIN_PASSWORD=YOUR_PASSWORD_HERE'
    volumes:
      - ./grafana_data:/var/lib/grafana
